### PR TITLE
Add a README

### PR DESCRIPTION
**Pull request by rhoslynroebuck**
This README explains the new purpose of the repo (since the update from 'state-utils' to 'nanover-utils'). Also updated the contributors.

### CODE REVIEW

**Review by hjstroud — APPROVED** [review]
Looks great! As long as all of the contributors to this point are present, I'm happy for this to be merged

**Comment by rhoslynroebuck** [comment]
Jonathan was the only contributor explicitly in the [nanover-py-recorder](https://github.com/IRL2/nanover-py-recorder) repo---he was the author of the commits and the only one listed in the contributors file. Is this accurate @Mohamed-Dhouioui, or did you also contribute to this code?

**Comment by Mohamed-Dhouioui** [comment]
I worked on manually stopping the recording. However, I haven't merged it yet. It is on a branch on my own repo called [fix-recording-stop](https://github.com/Mohamed-Dhouioui/nanover-py-recorder/tree/fix-recording-stop). I am planning to edit it one last edit and then merge it.

**Comment by Mohamed-Dhouioui** [comment]
Sure, that works for me.

**Review by Mohamed-Dhouioui — APPROVED** [review]

**Pull request merged**
